services:
  postgres:
    image: postgres:16-alpine
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: exam
      POSTGRES_PASSWORD: exam
      POSTGRES_DB: exam_portal
    volumes:
      - exam_pg_data:/var/lib/postgresql/data

volumes:
  exam_pg_data:
